name: Run PMD check
description: 'Performs a PMD check to verify that the code follows best practices.'

inputs:
  source:
    description: "Path to the source code being analysed."
    required: true
  rulesets:
    description: "Path to the rulesets being used, separated by comma."
    required: true
  checkDelta:
    description: "Flag indicating whether to check changed files only."
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: 'Setup PMD'
      shell: bash
      run: |
        wget -q https://github.com/pmd/pmd/releases/download/pmd_releases%2F7.0.0-rc2/pmd-bin-7.0.0-rc2.zip
        unzip -qq -d ~/pmd pmd-bin-7.0.0-rc2.zip > /dev/null
        echo "$HOME/pmd/pmd-bin-7.0.0-rc2/bin" >> $GITHUB_PATH

    - name: 'Run PMD'
      shell: bash
      run: |
        if [[ "${{ inputs.checkDelta }}" == "true" ]]; then
          pmd check --file-list ${{ inputs.source }} -R ${{ inputs.rulesets }} -f textcolor --no-cache 
        else
          pmd check -d ${{ inputs.source }} -R ${{ inputs.rulesets }} -f textcolor --no-cache 
        fi
