/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grupo4.proyectoso;

/**
 *
 * @author danac
 */
public class PopapAgregarProceso extends javax.swing.JFrame {

    /**
     * Creates new form AgregarProceso
     */
    public PopapAgregarProceso(Planificador planificador) {
        this.planificador = planificador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTTotalEjecucion = new javax.swing.JLabel();
        lblTRealizaES = new javax.swing.JLabel();
        lblTEsperaES = new javax.swing.JLabel();
        txtTTotalEjecucion = new javax.swing.JTextField();
        txtTRealizaES = new javax.swing.JTextField();
        txtTEsperaES = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        cboxTipoProceso = new javax.swing.JComboBox<>();
        btnAgregarProceso = new javax.swing.JButton();
        lblAgregarProceso = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spnPrioridad = new javax.swing.JSpinner();
        lblPrioridad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTTotalEjecucion.setText("Tiempo total de ejecución:");

        lblTRealizaES.setText("Tiempo en que realiza una E/S:");

        lblTEsperaES.setText("Tiempo de espera por E/S:");

        lblTipo.setText("Tipo:");

        cboxTipoProceso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SO", "Usuario" }));

        btnAgregarProceso.setText("Agregar");
        btnAgregarProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProcesoActionPerformed(evt);
            }
        });

        lblAgregarProceso.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAgregarProceso.setText("Agregar Proceso");

        jLabel1.setText("ms");

        jLabel2.setText("ms");

        jLabel3.setText("ms");

        spnPrioridad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));

        lblPrioridad.setText("Prioridad:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarProceso)
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAgregarProceso)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTipo)
                            .addComponent(lblTEsperaES)
                            .addComponent(lblTRealizaES)
                            .addComponent(lblTTotalEjecucion)
                            .addComponent(lblPrioridad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTTotalEjecucion, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTRealizaES, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTEsperaES, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(spnPrioridad, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cboxTipoProceso, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblAgregarProceso)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTTotalEjecucion)
                    .addComponent(txtTTotalEjecucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTRealizaES)
                    .addComponent(txtTRealizaES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTEsperaES)
                    .addComponent(txtTEsperaES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(cboxTipoProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrioridad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnAgregarProceso)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProcesoActionPerformed
        double tiempoEnCPU = Double.valueOf(txtTTotalEjecucion.getText());
        double periodoES = Double.valueOf(txtTRealizaES.getText());
        double esperaES = Double.valueOf(txtTEsperaES.getText());
        short prioridad = (short) (Short.valueOf(String.valueOf(spnPrioridad.getValue())) - 1);
        Proceso.Tipo tipo = Proceso.Tipo.USUARIO;
        if (String.valueOf(cboxTipoProceso.getSelectedItem()).equals("SO")) {
            tipo = Proceso.Tipo.SO;
        }
        if (this.planificador.insertarProceso(tiempoEnCPU, periodoES, esperaES, prioridad, tipo)) {
            this.dispose();
        }
    }//GEN-LAST:event_btnAgregarProcesoActionPerformed

    private Planificador planificador;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProceso;
    private javax.swing.JComboBox<String> cboxTipoProceso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAgregarProceso;
    private javax.swing.JLabel lblPrioridad;
    private javax.swing.JLabel lblTEsperaES;
    private javax.swing.JLabel lblTRealizaES;
    private javax.swing.JLabel lblTTotalEjecucion;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JSpinner spnPrioridad;
    private javax.swing.JTextField txtTEsperaES;
    private javax.swing.JTextField txtTRealizaES;
    private javax.swing.JTextField txtTTotalEjecucion;
    // End of variables declaration//GEN-END:variables
}
