/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grupo4.proyectoso;

/**
 *
 * @author danac
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInicial = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblTiempoEjecucion = new javax.swing.JLabel();
        spnCantProcesadores = new javax.swing.JSpinner();
        lblCantProcesadores = new javax.swing.JLabel();
        spnTiempoEjecucion = new javax.swing.JSpinner();
        btnIniciar = new javax.swing.JButton();
        panelProcesos = new javax.swing.JPanel();
        lblEnEjecucion = new javax.swing.JLabel();
        spanelEnEjecucion = new javax.swing.JScrollPane();
        tblEnEjecucion = new javax.swing.JTable();
        spanelListos = new javax.swing.JScrollPane();
        tblListos = new javax.swing.JTable();
        lblListos = new javax.swing.JLabel();
        lblBloqueados = new javax.swing.JLabel();
        spanelBloqueados = new javax.swing.JScrollPane();
        tblBloqueados = new javax.swing.JTable();
        btnAgregarProceso = new javax.swing.JButton();

        panelInicial.setName("Panel_inicial"); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        lblTitulo.setText("Planificador de procesos");

        lblTiempoEjecucion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblTiempoEjecucion.setText("Tiempo de ejecución de los procesos:");

        lblCantProcesadores.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblCantProcesadores.setText("Cantidad de procesadores:");

        btnIniciar.setText("Iniciar");

        javax.swing.GroupLayout panelInicialLayout = new javax.swing.GroupLayout(panelInicial);
        panelInicial.setLayout(panelInicialLayout);
        panelInicialLayout.setHorizontalGroup(
            panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicialLayout.createSequentialGroup()
                .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInicialLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(lblTitulo))
                    .addGroup(panelInicialLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInicialLayout.createSequentialGroup()
                                .addComponent(lblTiempoEjecucion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnTiempoEjecucion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelInicialLayout.createSequentialGroup()
                                .addComponent(lblCantProcesadores)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnCantProcesadores, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnIniciar))))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        panelInicialLayout.setVerticalGroup(
            panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicialLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblTitulo)
                .addGap(46, 46, 46)
                .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelInicialLayout.createSequentialGroup()
                        .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCantProcesadores)
                            .addComponent(spnCantProcesadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblTiempoEjecucion))
                    .addComponent(spnTiempoEjecucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnIniciar)
                .addContainerGap(431, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEnEjecucion.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        lblEnEjecucion.setText("Procesos en ejecución");

        tblEnEjecucion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spanelEnEjecucion.setViewportView(tblEnEjecucion);

        tblListos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spanelListos.setViewportView(tblListos);

        lblListos.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        lblListos.setText("Procesos listos");

        lblBloqueados.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        lblBloqueados.setText("Procesos bloqueados");

        tblBloqueados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spanelBloqueados.setViewportView(tblBloqueados);

        btnAgregarProceso.setText("Agregar Proceso");

        javax.swing.GroupLayout panelProcesosLayout = new javax.swing.GroupLayout(panelProcesos);
        panelProcesos.setLayout(panelProcesosLayout);
        panelProcesosLayout.setHorizontalGroup(
            panelProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProcesosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spanelListos, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelProcesosLayout.createSequentialGroup()
                        .addComponent(lblListos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarProceso)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(panelProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEnEjecucion)
                    .addComponent(spanelEnEjecucion, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBloqueados)
                    .addComponent(spanelBloqueados, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        panelProcesosLayout.setVerticalGroup(
            panelProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProcesosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnEjecucion)
                    .addComponent(lblListos)
                    .addComponent(btnAgregarProceso))
                .addGap(25, 25, 25)
                .addGroup(panelProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelProcesosLayout.createSequentialGroup()
                        .addComponent(spanelEnEjecucion, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(lblBloqueados)
                        .addGap(28, 28, 28)
                        .addComponent(spanelBloqueados, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(spanelListos))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 876, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelProcesos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelProcesos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProceso;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel lblBloqueados;
    private javax.swing.JLabel lblCantProcesadores;
    private javax.swing.JLabel lblEnEjecucion;
    private javax.swing.JLabel lblListos;
    private javax.swing.JLabel lblTiempoEjecucion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelInicial;
    private javax.swing.JPanel panelProcesos;
    private javax.swing.JScrollPane spanelBloqueados;
    private javax.swing.JScrollPane spanelEnEjecucion;
    private javax.swing.JScrollPane spanelListos;
    private javax.swing.JSpinner spnCantProcesadores;
    private javax.swing.JSpinner spnTiempoEjecucion;
    private javax.swing.JTable tblBloqueados;
    private javax.swing.JTable tblEnEjecucion;
    private javax.swing.JTable tblListos;
    // End of variables declaration//GEN-END:variables
}
