name: Process Pull Request
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  process_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get modified files
        id: pr_files
        run: |
          echo "Modified files:"
          echo ${{ steps.github.event.pull_request.base.sha }}
          echo ${{ steps.github.event.pull_request.head.sha }}
          curl -s \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/compare/${{ steps.github.event.pull_request.base.sha }}...${{ steps.github.event.pull_request.head.sha }}" \
            | jq -r '.files[].filename'

      # Use the list of modified files for further steps in the workflow
      - name: Use modified files
        run: |
          echo "Modified files: ${{ steps.pr_files.outputs.modified_files }}"
